let S={user:null,products:[],convs:[],orders:[],streamers:[],selected:null,socket:null};
const $=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),money=x=>"$"+Number(x).toFixed(0);
async function api(u,o={}){let r=await fetch(u,{...o,credentials:"include"}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function boot(){S.products=await api("/api/products");try{S.user=(await api("/api/auth/me")).user}catch{};if(S.user){connect();await load();dashboard()}else home()}
function nav(){return `<nav class=nav><div class="container navin"><a class=brand href="/">Agbota <b>Segun</b></a><div class=links><button onclick=home()>Store</button>${S.user?`<button onclick=dashboard()>Dashboard</button><button onclick=messages()>Messages ${unread()?`<span class=badge>${unread()}</span>`:""}</button><button onclick=logout()>Logout</button>`:`<button onclick=authBox('login')>Login</button><button class="btn primary" onclick=authBox('register')>Create Account</button>`}</div></div></nav>`}
function home(){document.querySelector("#app").innerHTML=nav()+`<section class=hero><div class=container><div class=eyebrow>Creator & Streamer Growth Strategies</div><h1>Build a smarter growth strategy for your channel.</h1><p>Professional digital strategy blueprints for creators and streamers who want a clearer plan for growing across the platforms they use.</p><div class=actions><button class="btn primary" onclick="document.querySelector('#products').scrollIntoView({behavior:'smooth'})">Explore Strategies</button><button class=btn onclick="authBox('register')">Create Streamer Account</button></div></div></section><section id=products class=section><div class=container><h2>Strategy Store</h2><p class=lead>Individual platform strategies and multi-platform bundles.</p><div class=grid>${S.products.map(p=>`<article class=card><span class=tag>${esc(p.category)}</span><h3>${esc(p.name)}</h3><p class=muted>${esc(p.description)}</p><div class=price>${money(p.price)}</div><button class="btn primary" onclick="order('${p.id}')">Order Strategy</button></article>`).join("")}</div></div></section><section class=section><div class=container><h2>How it works</h2><div class=steps><div class=step><b>01</b><h3>Choose</h3><p class=muted>Select a strategy.</p></div><div class=step><b>02</b><h3>Order</h3><p class=muted>Create an account and place your order.</p></div><div class=step><b>03</b><h3>Connect</h3><p class=muted>Message Agbota Segun directly.</p></div></div></div></section><footer class=footer><div class=container>© ${new Date().getFullYear()} Agbota Segun</div></footer>`}
function modal(x){document.body.insertAdjacentHTML("beforeend",`<div class=modal id=modal><div class=modalbox><button class=close onclick=modal.remove()>×</button>${x}</div></div>`)}
function authBox(mode){modal(`<h2>${mode==="login"?"Welcome back":"Create your streamer account"}</h2><form class=form onsubmit="auth(event,'${mode}')">${mode==="register"?`<input name=name placeholder="Your name" required>`:""}<input name=email type=email placeholder=Email required><input name=password type=password placeholder="Password (8+ characters)" minlength=8 required><button class="btn primary">${mode==="login"?"Log in":"Create account"}</button></form>`)}
async function auth(e,m){e.preventDefault();try{let f=new FormData(e.target),d=await api("/api/auth/"+m,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});S.user=d.user;document.getElementById("modal").remove();connect();await load();dashboard()}catch(x){alert(x.message)}}
async function logout(){await api("/api/auth/logout",{method:"POST"});location.reload()}
function connect(){if(S.socket)return;S.socket=io();S.socket.on("message:new",async m=>{if(S.selected===m.conversationId){add(m);await api("/api/conversations/"+m.conversationId+"/read",{method:"POST"})}await load();document.querySelector(".nav")?.replaceWith(new DOMParser().parseFromString(nav(),"text/html").body.firstChild)});S.socket.on("inbox:update",async()=>{await load();if(S.selected)renderContacts()})}
async function load(){S.convs=await api("/api/conversations");S.orders=await api("/api/orders");if(S.user.role==="owner")S.streamers=await api("/api/owner/streamers")}
function unread(){return S.convs.reduce((a,c)=>a+c.unread,0)}
function dashboard(){document.querySelector("#app").innerHTML=nav()+`<main class=dash><div class=container><div class=card><div class=eyebrow>${S.user.role==="owner"?"Owner Dashboard":"Streamer Dashboard"}</div><h2>Welcome, ${esc(S.user.name)}</h2><p class=lead>${S.user.role==="owner"?"All registered streamers are available in your contacts. You can message first.":"Your orders and permanent conversation are here."}</p></div><div class=dashgrid style="margin-top:15px"><aside class=side><div class=sidehead><b>Messages</b><div class=muted>🔴 ${unread()} unread</div></div><input class="search form" placeholder="Search streamers" oninput="filter(this.value)"><div id=contacts>${S.convs.map(c=>contact(c)).join("")}</div></aside><section id=chat class=chat><div class=chathead><b>Select a conversation</b></div><div class=msgs style="justify-content:center;color:#9da8bc">Select a streamer.</div></section></div><div class=card style="margin-top:15px"><h3>Orders</h3>${S.orders.length?S.orders.map(o=>`<div class=order><b>${esc(o.orderNumber)}</b> — ${esc(o.product?.name||"Strategy")} <span class=status>${esc(o.status)}</span><div class=muted>${money(o.price)} · ${new Date(o.createdAt).toLocaleString()}</div>${S.user.role==="owner"&&o.paymentStatus!=="Paid"?`<button class="btn primary" onclick="confirmPay('${o.id}')">Confirm Payment</button>`:""}${o.receiptUrl?` <a class=btn href="${o.receiptUrl}" target=_blank>Receipt</a>`:""}</div>`).join(""):"<p class=muted>No orders yet.</p>"}</div></div></main>`}
function contact(c){return `<button class=contact onclick="openChat('${c.id}')"><b>${esc(c.other?.name||"Unknown")}</b>${c.unread?` <span class=badge>${c.unread}</span>`:""}<small>${c.lastMessage?esc(c.lastMessage):`<span class=new>NEW STREAMER — you can message first</span>`}</small></button>`}
function renderContacts(){$("#contacts").innerHTML=S.convs.map(contact).join("")}
function filter(q){document.querySelectorAll(".contact").forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q.toLowerCase())?"block":"none")}
async function openChat(id){S.selected=id;let c=S.convs.find(x=>x.id===id),ms=await api("/api/conversations/"+id+"/messages");$("#chat").innerHTML=`<div class=chathead><b>${esc(c.other.name)}</b><span class=muted>${c.other.role==="streamer"?"Streamer":"Owner"}</span></div><div class=msgs id=msgs>${ms.map(msg).join("")}</div><form class=composer onsubmit="sendText(event)"><input id=text placeholder="Write a message..." autocomplete=off><input id=file class=hidden type=file onchange=sendFile()><button type=button class=icon onclick="pick('image/*')">🖼️</button><button type=button class=icon onclick="pick('*/*')">📎</button><button type=button class=icon onclick=voice()>🎙️</button><button class="btn primary">Send</button></form>`;S.socket?.emit("conversation:join",id);scroll()}
function msg(m){let b=esc(m.text);if(m.type==="image"&&m.fileUrl)b=`<img src="${m.fileUrl}">`;else if(m.type==="voice"&&m.fileUrl)b=`<audio controls src="${m.fileUrl}"></audio>`;else if(m.fileUrl)b=`<a href="${m.fileUrl}" target=_blank>${esc(m.fileName||"Attachment")}</a>`;return `<div class="bubble ${m.senderId===S.user.id?"mine":""}">${b}<small>${new Date(m.createdAt).toLocaleString()}</small></div>`}
function add(m){$("#msgs")?.insertAdjacentHTML("beforeend",msg(m));scroll()}
function scroll(){let x=$("#msgs");if(x)x.scrollTop=x.scrollHeight}
async function sendText(e){e.preventDefault();let x=$("#text"),t=x.value.trim();if(!t)return;let f=new FormData();f.append("type","text");f.append("text",t);await api("/api/conversations/"+S.selected+"/messages",{method:"POST",body:f});x.value=""}
function pick(a){let x=$("#file");x.accept=a;x.click()}
async function sendFile(){let f=$("#file").files[0];if(!f)return;let d=new FormData();d.append("file",f);d.append("type",f.type.startsWith("image/")?"image":"file");await api("/api/conversations/"+S.selected+"/messages",{method:"POST",body:d});$("#file").value=""}
let rec,chunks=[];async function voice(){if(rec?.state==="recording"){rec.stop();return}try{let st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{let d=new FormData();d.append("file",new Blob(chunks,{type:"audio/webm"}),"voice.webm");d.append("type","voice");await api("/api/conversations/"+S.selected+"/messages",{method:"POST",body:d});st.getTracks().forEach(t=>t.stop())};rec.start();alert("Recording started. Tap the microphone again to stop and send.")}catch(e){alert("Microphone permission was denied.")}}
async function order(id){if(!S.user)return authBox("register");try{let o=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:id})});modal(`<h2>Order ${esc(o.orderNumber)}</h2><p>Send <b>${money(o.price)}</b> in BTC.</p><div class=btc>${esc(o.btcAddress)}</div><p class=muted>After paying, upload your receipt and message Agbota Segun. For PayPal, use Messages to request instructions.</p><button class="btn primary" onclick=modal.remove();dashboard()>Go to Dashboard</button>`);await load()}catch(e){alert(e.message)}}
async function confirmPay(id){await api("/api/orders/"+id+"/confirm",{method:"POST"});await load();dashboard()}
function messages(){dashboard()}
boot();